sudo: required
services:
  - docker

before_install:
  - docker build -t pisckitama/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true pisckitama/react-test npm test

after_success:
  - docker build -t pisckitama/multi-client ./client
  - docker build -t pisckitama/multi-nginx ./nginx
  - docker build -t pisckitama/multi-server ./server
  - docker build -t pisckitama/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those image and push them to docker hub
  - docker push pisckitama/multi-client
  - docker push pisckitama/multi-nginx
  - docker push pisckitama/multi-server
  - docker push pisckitama/multi-worker

deploy:
  provider: elasticbeanstalk
  region: "ap-southeast-1"
  app: "multi-docker"
  env: "MultiDocker-env"
  bucket_name: "elasticbeanstalk-ap-southeast-1-558947512759"
  bucket_path: "docker-multi"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY

language: generic  